/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String _kFontPkg = null;
  static const IconData chat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData community = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cricket = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hockey_player = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData planet_earth = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData web_search_engine = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit_1 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
